server:
  port: 8081

spring:
  application:
    name: oauth2-securiity
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yin7372175240000
    jdbc-url: jdbc:mysql://47.94.81.96:3306/oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1


  security:
    user:
      name: admin2
      password: 123


mybatis:
  type-aliases-package: com.yaolong.oauth2.server.domain
  mapper-locations: classpath:mapper/*.xml